# Generated by Django 3.0.4 on 2020-04-25 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('human_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wg_identifier', models.BigIntegerField(db_index=True, default=0)),
                ('name', models.CharField(max_length=200)),
                ('tier', models.IntegerField(default=0)),
                ('playercount', models.IntegerField(default=0)),
                ('average_wr', models.DecimalField(decimal_places=5, default=0, max_digits=6)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('economy_type', models.IntegerField(choices=[(1, 'Techtree'), (2, 'Premium')])),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statparser.Nation')),
            ],
        ),
        migrations.CreateModel(
            name='TankType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wg_user', models.IntegerField(default=0, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField(default=0)),
                ('battles', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statparser.Tank')),
                ('wg_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statparser.User', to_field='wg_user')),
            ],
        ),
        migrations.AddField(
            model_name='tank',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statparser.TankType'),
        ),
    ]
