# Generated by Django 3.0.4 on 2020-04-29 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statparser', '0002_auto_20200425_1719'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userstat',
            index=models.Index(fields=['wg_user', 'tank'], name='statparser__wg_user_cadbc0_idx'),
        ),
        migrations.AddIndex(
            model_name='userstat',
            index=models.Index(fields=['tank', 'wg_user'], name='statparser__tank_id_c51912_idx'),
        ),
        migrations.AddIndex(
            model_name='userstat',
            index=models.Index(fields=['tank', 'updated_at'], name='statparser__tank_id_225564_idx'),
        ),
        migrations.AddConstraint(
            model_name='userstat',
            constraint=models.UniqueConstraint(fields=('wg_user', 'tank'), name='unique_tank_entry'),
        ),
    ]
