# Generated by Django 3.0.4 on 2020-04-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statparser', '0003_auto_20200428_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstat',
            name='capture_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstat',
            name='damage_dealt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstat',
            name='damage_received',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstat',
            name='frags',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstat',
            name='hits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstat',
            name='hits_percents',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstat',
            name='spotted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstat',
            name='stun_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstat',
            name='survived_battles',
            field=models.IntegerField(default=0),
        ),
    ]
