# Generated by Django 3.0.4 on 2020-04-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statparser', '0004_auto_20200429_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='img',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
